package com.trang.ez_mobile.util;

import java.util.HashMap;

public class Language {
    public static HashMap<String, String> hashMap = new HashMap<>();

    public Language(int check) {
        switch (check) {
            case 1:
                putdataLangueViet();
                break;
            case 2:
                putdataLangueAnh();
                break;
        }

    }

    public void putdataLangueViet() {
        hashMap = new HashMap<>();
        hashMap.put("Limit balance", "Hạn mức còn lại :");
        hashMap.put("Aggregate buying power", "Sức mua tổng hợp :");
        hashMap.put("Choose category", "Bạn chưa chọn danh mục!");
        hashMap.put("Choose your category", "Chọn danh mục");
        hashMap.put("Quantity should be more than 100","số lượng phải lớn hơn 100");
        hashMap.put("Cancel", "Hủy bỏ");
        hashMap.put("Network connection Error", "Mất kết nối tới Wifi");
        hashMap.put("Quantity should be more than 0 and  must be lesser than 100", "Số lượng phải lớn hơn 0 và nhỏ hơn 100");
        hashMap.put("Quantity should be more than 10 and must be a multiple of 10", "Số lượng phải lớn hơn 10 và phải là bội số của 10 ");
        hashMap.put("Quantity should be more than 100 and must be a multiple of 100", "Số lượng phải lớn hơn 100 và phải là bội số của 100 ");
        hashMap.put("Margin Account Detail", "Chi Tiết Tài Khoản Ký Quỹ");
        hashMap.put("Securities Symbol", "Mã CK");
        hashMap.put("Cancel Order Successful", "Hủy Lệnh Thành Công");
        hashMap.put("Session Logout", "Mất Session");
        hashMap.put("Available", "KL có sẵn");
        hashMap.put("Pending for Settlement", "KL chờ về");
        hashMap.put("Pending for Corporate Actions", "KL quyền chờ về");
        hashMap.put("MarketData Price", "Giá TT");
        hashMap.put("Rate (Right)", "TLSM (Quyền)");
        hashMap.put("Securities-leveraged buying power", "Sức mua bấy từ CK");
        hashMap.put("Cash", "Tiền mặt");
        hashMap.put("Cash on hold", "Tiền treo mua");
        hashMap.put("Cash pending payment", "Tiền bán chờ về");
        hashMap.put("Cash in transit", "Tiền đang chuyển");
        hashMap.put("Basic buying power", "Sức mua cơ sở :");
        hashMap.put("Total credit limit", "Tổng hạn mức");
        hashMap.put("Outstanding debt", "Dư nợ");
        hashMap.put("Accumulated interest", "Lãi vay kq lũy kế");
        hashMap.put("Current R", "R hiện tại");
        hashMap.put("Amount Called", "ST cần bổ sung");
        hashMap.put("Rxl", "Mức XL");
        hashMap.put("Account Details", "Chi tiết tài khoản");
        hashMap.put("Securities", "Chi tiết CK");

        hashMap.put("Cashbuy:", "Giá trị lệnh mua:");
        hashMap.put("Available Stock", "Số dư Chứng Khoán");
        hashMap.put("The amount of the amount of a balance", "Số tiền gửi không được lớn hơn số dư");
        hashMap.put("Please input name", "Vui lòng nhập tên tài khoản!");
        hashMap.put("Special characters", "Nội dung là không có dấu và ký tự đặc biệt");
        hashMap.put("Special characters name", "Tên tài khoản là không có dấu và ký tự đặc biệt");
        hashMap.put("Sức mua CK còn lại:", "Sức mua CK còn lại:");
        hashMap.put("Not response", "Lỗi không xác định");
        hashMap.put("Pending Order", "Lệnh Chờ Khớp");
        hashMap.put("Today's Orders", "Lệnh Trong Ngày");
        hashMap.put("Other Money:", "Tiền khác:");
        hashMap.put("Updated to:", "Cập nhật đến :");
        hashMap.put("Please update your app !", "Xin mời cập nhật phiên bản mới !");
        hashMap.put("Current version is out of date. Please upgrade to new version!", "Phiên bản ứng dụng đang dùng đã cũ. Quý khách vui lòng cập nhật phiên bản mới!");
        hashMap.put("Delete Watchlist", "Xóa danh mục");
        hashMap.put("MarketData is opened", "Thị Trường Mở Cửa");
        hashMap.put("Skip", "Bỏ qua");
        hashMap.put("The quantity each split order must be bigger than 1000", "Khối lượng tối thiểu là 1000");
        hashMap.put("was setted as default Watchlist", "đã được đặt thành Danh mục Mặc định");
        hashMap.put("News", "Tin Tức");
        hashMap.put("Sellable", "Có thể bán");
        hashMap.put("CASH", "Thường");
        hashMap.put("MARGIN", "Ký quỹ");
        hashMap.put("January", "Tháng 1");
        hashMap.put("February", "Tháng 2");
        hashMap.put("March", "Tháng 3");
        hashMap.put("April", "Tháng 4");
        hashMap.put("May", "Tháng 5");
        hashMap.put("June", "Tháng 6");
        hashMap.put("July", "Tháng 7");
        hashMap.put("August", "Tháng 8");
        hashMap.put("September", "Tháng 9");
        hashMap.put("October", "Tháng 10");
        hashMap.put("November", "Tháng 11");
        hashMap.put("December", "Tháng 12");
        hashMap.put("tháng 1", "Tháng 1");
        hashMap.put("tháng 2", "Tháng 2");
        hashMap.put("tháng 3", "Tháng 3");
        hashMap.put("tháng 4", "Tháng 4");
        hashMap.put("tháng 5", "Tháng 5");
        hashMap.put("tháng 6", "Tháng 6");
        hashMap.put("tháng 7", "Tháng 7");
        hashMap.put("tháng 8", "Tháng 8");
        hashMap.put("tháng 9", "Tháng 9");
        hashMap.put("tháng 10", "Tháng 10");
        hashMap.put("tháng 11", "Tháng 11");
        hashMap.put("tháng 12", "Tháng 12");
        hashMap.put("Price, Quantity unchanged", "Giá, KL chưa thay đổi");
        hashMap.put("Add WatchList Name", "thêm danh mục mới");
        hashMap.put("The Cash Receive must be less than", "Số tiền vay không lớn hơn");
        hashMap.put("Switch account", "Đăng nhập tài khoản khác");
        hashMap.put("Normal order quantity should be less than 500.000 (HOSE stock). You should split order.", "Khối lượng Báo giá phải nhỏ hơn 500.000 đối với sàn HOSE. Bạn phải tách lệnh.");
        hashMap.put("+/-", "+/-");
        hashMap.put("P.B3", "G.M3");
        hashMap.put("Q.B3", "KL.M3");
        hashMap.put("P.B2", "G.M2");
        hashMap.put("Q.B2", "KL.M2");
        hashMap.put("P.B1", "G.M1");
        hashMap.put("Q.B1", "KL.M1");

        hashMap.put("P.S1", "G.B1");
        hashMap.put("Q.S1", "KL.B1");
        hashMap.put("P.S2", "G.B2");
        hashMap.put("Q.S2", "KL.B2");
        hashMap.put("P.S3", "G.B3");
        hashMap.put("Q.S3", "KL.B3");
        hashMap.put("newshomee", "tintiengviet");
        hashMap.put("There is no information of indice", "Chưa có thông tin chỉ số");
        hashMap.put("eventshomee", "sukienhometiengviet");
        hashMap.put("Sell Oddlot History", "Lịch sử bán CK lô lẻ");
        hashMap.put("Extendable", "Có thể gia hạn");
        hashMap.put("Date", "Ngày");
        hashMap.put("Repay", "Trả nợ");
        hashMap.put("Renew", "Gia hạn");
        hashMap.put("Please input Amount", "Chưa nhập Số tiền Chuyển khoản");
        hashMap.put("Search", "Tìm kiếm mã chứng khoán");
        hashMap.put("Select Template", "Chọn Biểu mẫu");
        hashMap.put("Order History", "Lịch sử đặt lệnh");
        hashMap.put("Intraday Trading Result", "Kết quả  khớp lệnh");
        hashMap.put("Match Price", "Giá Khớp");
        hashMap.put("Total Vol", "Tổng KL");
        hashMap.put("Quantity should be less than 999.999", "Số lượng nên nhỏ hơn 999.999");
        hashMap.put("Qty", "SL");
        hashMap.put("Most Active", "GD Nhiều");
        hashMap.put("New Contract Date:", "Ngày Hợp đồng Mới:");
        hashMap.put("Please enter Receiver Name", "Chưa nhập Tên Người nhận");
        hashMap.put("Floor", "Sàn");
        hashMap.put("Cancel Order", "Hủy lệnh");
        hashMap.put("Modify Order", "Sửa lệnh");
        hashMap.put("Back", "Quay Lại");
        hashMap.put("Bene.'s Account not exist", "Tài khoản Người nhận không tồn tại");
        hashMap.put("Transfer History", "Lịch sử chuyển tiền");
        hashMap.put("Contract", "Hợp đồng");
        hashMap.put("Please select Bank", "Chưa chọn Ngân hàng");
        hashMap.put("New Expriry Date:", "Ngày hết hạn mới:");
        hashMap.put("Expriry Date:", "Ngày hết hạn:");
        hashMap.put("Content", "Nội dung");
        hashMap.put("Held for buying orders:", "Đang treo:");
        hashMap.put("Please input Account", "Chưa nhập Tài khoản Người nhận");
        hashMap.put("SELL", "Bán");
        hashMap.put("BUY", "Mua");
        hashMap.put("P/L", "Lãi/Lỗ");

        hashMap.put("Can not modify oddlot order to normal order", "Không thể sửa lệnh lô chẵn thành lô lẻ");
        hashMap.put("Can not modify normal order to oddlot order", "Không thể sửa lệnh lô lẻ thành lô chẵn");
        hashMap.put("Margin Amount", "Ký Quỹ");
        hashMap.put("Select Account To Transfer", "Chọn Tài khoản Người nhận");
        hashMap.put("Quantity", "Số Lượng");
        hashMap.put("Transfer Description", "Nội dung Chuyển tiền");
        hashMap.put("Confirm Buy", "Xác nhận Mua");
        hashMap.put("Please select Date To", "Chưa chọn Ngày kết thúc");
        hashMap.put("Ref", "TC");
        hashMap.put("Stock", "Chứng khoán");
        hashMap.put("Please enter Transfer Description", "Chưa nhập Nội dung Chuyển tiền");
        hashMap.put("Normal Stock", "Chứng khoán Thường");
        hashMap.put("Term:", "Lệnh");
        hashMap.put("Buy", "Mua");
        hashMap.put("Pay Amount:", "Thanh toán:");
        hashMap.put("Real Estate News", "Bất động sản");
        hashMap.put("New Charge Rate:", "Tỉ lệ Phí Mới:");
        hashMap.put("Breaking time", "Nghỉ trưa");
        hashMap.put("Cancel Transfer Successfully", "Đã huỷ Giao dịch Chuyển tiền");
        hashMap.put("Favorites", "Yêu Thích");
        hashMap.put("Select Branch", "Chọn Chi nhánh");
        hashMap.put("Advance Amount:", "Ứng trước:");
        hashMap.put("FPTS News", "Tin tức FPTS");
        hashMap.put("Quantity must be lesser than 20.000", "Số lượng giao dịch không được lớn hơn 20.000");
        hashMap.put("Get Quotes", "Mã Chứng Khoán");
        hashMap.put("Account:", "Tài khoản:");
        hashMap.put("Please select Province", "Chưa chọn Tỉnh thành");
        hashMap.put("Financial Figures", "Chỉ Số & Chỉ Tiêu Tài Chính");
        hashMap.put("Cash Balance:", "Số dư Tiền");
        hashMap.put("Available Cash:", "Số dư Tiền");

        hashMap.put("Economy News", "Kinh tế vĩ mô");
        hashMap.put("WatchList Name", "Tên Danh Mục");
        hashMap.put("Price", "Giá");
        hashMap.put("New Expire Date:", "Ngày Hết hạn Mới:");
        hashMap.put("Setting", "Thiết Lập");
        hashMap.put("Home", "Trang Chủ");
        hashMap.put("Remain Room:", "Khối lượng Còn lại:");
        hashMap.put("Quantity each Order:", "Khối lượng mỗi Lệnh:");

        hashMap.put("Finance Overview", "Tổng Quan Tài Chính");
        hashMap.put("Trading Password", "Mật khẩu Giao dịch");
        hashMap.put("Please Select Account To Transfer", "Chưa chọn Tài khoản Người nhận");
        hashMap.put("Money Transfer", "Chuyển Tiền");

        hashMap.put("Margin Account Details", "Báo Cáo Ký Quỹ");

        hashMap.put("Open", "Mở");
        hashMap.put("Close", "Đóng");
        hashMap.put("Margin:", "Ký Quỹ");
        hashMap.put("Finance & Banking News", "Tài chính - Ngân hàng");
        hashMap.put("WatchList must have at least one company", "Danh mục phải có ít nhất 1 mã");
        hashMap.put("Overview", "Tổng Quan");
        hashMap.put("Cur. Mor Amount:", "Tổng Mor:");
        hashMap.put("Current Room:", "Khối lượng Hiện tại:");
        hashMap.put("Forei.Sell", "NN Bán");
        hashMap.put("Commodity News", "Thị trường hoàng hoá");
        hashMap.put("Val", "GT");
        hashMap.put("Symbol:", "Mã CK :");
        hashMap.put("Symbol Search", "Mã CK");
        hashMap.put("Not enough stock balance", "Số lượng không đủ để cầm cố");

        hashMap.put("Symbol", "Mã CK");
        hashMap.put("Contract No", "Số hợp đồng");
        hashMap.put("Please enter Price", "Chưa nhập Giá");
        hashMap.put("Please enter Pay Amount", "Chưa nhập Số tiền Thanh toán");
        hashMap.put("cannot buy Margin", "không thể mua Ký Quỹ");
        hashMap.put("Available Balance:", "Số dư hiện tại:");
        hashMap.put("No. of days:", "Số ngày tính lãi:");
        hashMap.put("Pay Amount:", "Số tiền trả");
        hashMap.put("Rate (%/day):", "Lãi suất (%/ngày):");
        hashMap.put("Interest:", "Lãi vay:");
        hashMap.put("Fee:", "Phí tạm tính:");
        hashMap.put("Fee", "Phí");
        hashMap.put("Please select Branch", "Chưa chọn Chi nhánh");
        hashMap.put("Remember Account", "Ghi Nhớ Tài Khoản");
        hashMap.put("World News", "Chỉ số thế giới");
        hashMap.put("Price must be a multiple of", "Giá phải là bội số của ");
        hashMap.put("Price must be a multiple of 100", "Giá phải là bội số của 100");
        hashMap.put("Price must be a multiple of 10", "Giá phải là bội số của 10");
        hashMap.put("Price must be a multiple of 1", "Giá phải là bội số của 1");
        hashMap.put("Floor Price", "Giá Sàn");
        hashMap.put("Cash & Stock", "Tiền & Chứng Khoán");
        hashMap.put("Please select Date From", "Chưa chọn Ngày bắt đầu");
        hashMap.put("Contract:", "Hợp đồng:");
        hashMap.put("Branch:", "Chi nhánh:");
        hashMap.put("Sell Price", "Giá Bán");
        hashMap.put("New Price:", "Giá mới");
        hashMap.put("Cash:", "Tiền mặt");
        hashMap.put("New Interest Rate (%/day):", "Lãi suất mới (%/ngày):");
        hashMap.put("Stock balance is not enough", "Tài khoản không đủ chứng khoán");
        hashMap.put("Buy Price", "Giá ");
        hashMap.put("MarketData News", "Thị trường Chứng khoán");
        hashMap.put("Account", "Tài khoản");
        hashMap.put("Matching:", "Khớp:");
        hashMap.put("Confirm Sell", "Xác nhận Bán");
        hashMap.put("Quantity should be more than 0", "Số lượng phải lớn hơn 0");
        hashMap.put("Quantity should be more than 10", "Số lượng phải lớn hơn 10");
        hashMap.put("Quantity should be more than 999", "Số lượng phải lớn hơn 999");
        hashMap.put("Chart", "Biểu Đồ");
        hashMap.put("Charge Rate:", "Tỉ lệ Phí:");
        hashMap.put("Putthrough:", "Thoả Thuận:");
        hashMap.put("Ratios (%):", "Tỉ lệ Sở hữu (%):");
        hashMap.put("Features", "Tính Năng");
        hashMap.put("Pay amount must be smaller than current Mar/Mor amount", "Tổng thanh toán phải nhỏ hơn Tổng Ký Quỹ");
        hashMap.put("Modify Order Successful", "Sửa lệnh Thành công");
        hashMap.put("Vol:", "KL:");
        hashMap.put("bil", "tỷ");
        hashMap.put("Sell Quantity", "KL Bán");
        hashMap.put("Sell", "Bán");
        hashMap.put("World Indexes", "Chỉ Số Thế Giới");
        hashMap.put("Mortgage", "Cầm cố");
        hashMap.put("Symbol", "Mã CK");
        hashMap.put("Price should be less than 999.999.999", "Giá nên nhỏ hơn 999.999");
        hashMap.put("Financial Ratios", "Chỉ Tiêu");
        hashMap.put("Margin Stock", "Chứng khoán Ký Quỹ");
        hashMap.put("Low", "Thấp");
        hashMap.put("Exit", "Thoát");
        hashMap.put("Place Orders", "Đặt Lệnh");
        hashMap.put("Available Stock:", "Số dư CK");
        hashMap.put("Payment", "Trả nợ");
        hashMap.put("Stock Balance", "Chứng Khoán");
        hashMap.put("Please enter Receiver Account", "Chưa nhập Tài khoản Người nhận");
        hashMap.put("Expire Date:", "Ngày Hết hạn:");
        hashMap.put("Bank:", "Ngân hàng:");
        hashMap.put("From Date", "Từ ngày");
        hashMap.put("Total:", "Tổng:");
        hashMap.put("Pending Buy Orders:", "Đang treo:");
        hashMap.put("Change", "Thay Đổi");
        hashMap.put("Margin", "Ký Quỹ");
        hashMap.put("Date Count:", "Số ngày:");
        hashMap.put("Asset Report", "Báo Cáo Tài Sản");
        hashMap.put("Quantity must be a multiple of 10", "Số lượng phải là bội số của 10");
        hashMap.put("Select Bank", "Chọn Ngân hàng");
        hashMap.put("Login", "Đăng nhập");
        hashMap.put("Sell Oddlot", "Bán Lô Lẻ");
        hashMap.put("BANK", "NGÂN HÀNG");
        hashMap.put("Amount:", "Số tiền");
        hashMap.put("Account:", "Tài khoản");
        hashMap.put("Name:", "Tên");
        hashMap.put("Bank:", "Ngân hàng");
        hashMap.put("Province:", "Tỉnh thành");
        hashMap.put("Branch:", "Chi nhánh");
        hashMap.put("Estimated Fee:", "Phí tạm tính");
        hashMap.put("Select Template", "Chọn Biểu mẫu");
        hashMap.put("Select Bank", "Chọn Ngân hàng");
        hashMap.put("Select Province", "Chọn Tỉnh thành");
        hashMap.put("Select Branch", "Chọn Chi nhánh");
        hashMap.put("Transfer Description", "Nội dung Chuyển tiền");
        hashMap.put("Amount", "Số Tiền");

        hashMap.put("is not in the Margin stock list", "không có trong danh mục ký quỹ");
        hashMap.put("Detail", "Chi tiết");
        hashMap.put("Request has been executed successfully!", "Giao dịch Thành công!");
        hashMap.put("MarketData is opening", "Thị trường Mở cửa");
        hashMap.put("Provisional Fee:", "Phí Tạm thu:");
        hashMap.put("Mor Amount:", "Tổng Mor:");
        hashMap.put("Company News", "Tin Tức Công Ty");
        hashMap.put("Foreign Ownership", "Thông Tin Nước Ngoài");
        hashMap.put("Forei.Buy", "NN Mua");
        hashMap.put("Volume", "Khối Lượng");
        hashMap.put("Name", "Tên");
        hashMap.put("Value", "Giá Trị");
        hashMap.put("Total Room:", "Khối lượng Được mua:");
        hashMap.put("Please input WatchList Name", "Tên Danh Mục");
        hashMap.put("Order List", "Danh sách lệnh đặt");
        hashMap.put("Please enter Symbol", "Chưa nhập Mã CK");
        hashMap.put("Modify Order", "Sửa Lệnh");
        hashMap.put("Cancel/Modify Order", "Hủy/Sửa lệnh");
        hashMap.put("Headlines", "Tin Tức");
        hashMap.put("Symbol is already in Quotes", "Mã đã có trong danh mục");
        hashMap.put("Cur. Mar Amount:", "Tổng Mar:");
        hashMap.put("Open Qty", "SL Mở cửa");
        hashMap.put("Input invalid number", "Nhập sai Số");
        hashMap.put("Last", "Giá");
        hashMap.put("Last ", "Giá Khớp");
        hashMap.put("Pending Qty", "Đang treo");
        hashMap.put("Top Losers", "Giảm Mạnh");
        hashMap.put("Province", "Tỉnh thành");
        hashMap.put("Putthrough", "Thoả thuận");
        hashMap.put("MarketData Overview", "Tổng Quan Thị Trường");
        hashMap.put("Charge Amount:", "Tổng Phí:");
        hashMap.put("Select Province", "Chọn Tỉnh thành");
        hashMap.put("To Date", "Đến ngày");
        hashMap.put("Password:", "Mật khẩu");
        hashMap.put("Dashboard", "Trang Chủ");
        hashMap.put("Please enter Quantity", "Chưa nhập Số lượng");
        hashMap.put("Cash Total:", "Tổng giá trị");
        hashMap.put("Your trading password is incorrect", "Sai Mật khẩu Giao dịch");
        hashMap.put("Mar Amount:", "Tổng Mar:");
        hashMap.put("Value:", "GT:");
        hashMap.put("Price:", "Giá :");
        hashMap.put("Quantity:", "Số lượng");
        hashMap.put("Please enter your account", "Chưa nhập Tài khoản");
        hashMap.put("Logged out", "Đã đăng xuất");
        hashMap.put("Up/Down stocks", "Số mã Tăng/Giảm");
        hashMap.put("The quantity should be lesser than 999.999", "Số lượng nên nhỏ hơn 999.999");
        hashMap.put("Events", "Lịch Sự Kiện");
        hashMap.put("Exchange:", "Sàn GD");
        hashMap.put("Ceil", "Trần");
        hashMap.put("Quantity must be a multiple of 100", "Số lượng phải là bội số của 100");
        hashMap.put("Delete", "Xoá");
        hashMap.put("Select Template", "Chọn Biểu mẫu");
        hashMap.put("Top Gainers", "Tăng Mạnh");
        hashMap.put("Please select Bank", "Chưa chọn Ngân hàng");
        hashMap.put("Mkt.Price", "Giá TT");
        hashMap.put("Watch List", "Bảng Giá");
        hashMap.put("Cash balance is not enough", "Tài khoản không đủ tiền");
        hashMap.put("High", "Cao");
        hashMap.put("Confirm", "Xác nhận");
        hashMap.put("The price must be a multiple of", "Giá phải là bội số của");
        hashMap.put("Match", "KL Khớp");
        hashMap.put("Please enter Cash To Transfer", "Chưa nhập Số tiền Chuyển khoản");
        hashMap.put("Cancel Order", "Huỷ Lệnh");
        hashMap.put("Vol", "KL");
        hashMap.put("Pending", "Chờ");
        hashMap.put("Cash Balance", "Tiền");
        hashMap.put("Add Watch List", "Thêm Danh Mục");
        hashMap.put("Cash Receive:", "Số tiền vay :");
        hashMap.put("Foreign Sell:", "NN Bán:");
        hashMap.put("Password", "Mật khẩu");
        hashMap.put("The quantity must be lesser than", "Số lượng phải nhỏ hơn");
        hashMap.put("Price must be between", "Giá phải nằm trong khoảng");
        hashMap.put("Stock is not enough to mortgage", "Số lượng không đủ để cầm cố");
        hashMap.put("Side:", "Mua Bán");
        hashMap.put("Price should be more than 0", "Giá phải lớn hơn 0");
        hashMap.put("MarketData was closed", "Thị trường Đóng cửa");
        hashMap.put("Indices", "Chỉ Số");
        hashMap.put("Indexes", "Chỉ Số");
        hashMap.put("Buy Quantity", "KL Mua");
        hashMap.put("Pay Date:", "Hạn Thanh toán:");
        hashMap.put("Ezmargin Sell", "Bán Ký Quỹ");
        hashMap.put("Rate:", "Tỉ Lệ :");
        hashMap.put("Rate", "Tỉ lệ");
        hashMap.put("Avg.Price", "Giá TB");
        hashMap.put("New Qty:", "KL mới");
        hashMap.put("Change Qty:", "KL thay đổi");
        hashMap.put("Ref Price", "Giá TC");
        hashMap.put("Foreign Buy:", "NN Mua:");
        hashMap.put("Total", "Tổng");
        hashMap.put("Available Qty", "SL Hiện tại");
        hashMap.put("Quantity must be less than 500.000", "Số lượng giao dịch không quá 500.000");
        hashMap.put("Total Payment:", "Tổng:");
        hashMap.put("Please enter your password", "Chưa nhập Mật khẩu");
        hashMap.put("Login with other account", "Đăng nhập tài khoản khác");
        hashMap.put("Symbol does not exist", "Mã CK không tồn tại");
        hashMap.put("Restrict Stock", "Chứng khoán Hạn chế");
        hashMap.put("Contract Date:", "Ngày Hợp đồng:");
        hashMap.put("Contract Date", "Ngày Hợp đồng");
        hashMap.put("Advance Report", "Lịch Sử Ứng Trước");
        hashMap.put("Receiver Account does not exsit", "Tài khoản Người nhận không tồn tại");
        hashMap.put("Member Area", "Thành Viên");
        hashMap.put("Member", "Thành Viên");
        hashMap.put("Extend", "Gia hạn");
        hashMap.put("Cash", "Tiền mặt");
        hashMap.put("Exit", "Thoát");
//        hashMap.put("Mortgage Order", "Hợp đồng cầm cố");
        hashMap.put("Please enter Trading Password", "Chưa nhập Mật khẩu Giao dịch");
        hashMap.put("Ceil Price", "Giá Trần");
        hashMap.put("Renew", "Gia hạn");
        hashMap.put("Language", "Ngôn Ngữ");
        hashMap.put("Type:", "Loại GD");
        hashMap.put("Cash Being Transferred:", "Đang chuyển:");
        hashMap.put("Logout", "Đăng xuất");
        hashMap.put("Key FS Items", "Chỉ Số");
        hashMap.put("Amount:", "Số tiền");
        hashMap.put("Foreign-owned Ratio (%):", "Tỉ lệ Sở hữu (%):");
        hashMap.put("Order Type:", "Loại lệnh :");
        hashMap.put("Buy/Sell", "Mua bán");

        hashMap.put("Time", "Thời Gian");
        hashMap.put("Order Type", "Loại lệnh");
        hashMap.put("Status", "Tình trạng");
        hashMap.put("Remaining Loan Amt:", "Dư nợ ký quỹ còn lại:");
        hashMap.put("Product Type", "Loại GD");
        hashMap.put("Exchange", "Sàn");
        hashMap.put("Order No.", "SHL");
        hashMap.put("Account", "Tài khoản");
        hashMap.put("Remain Qty", "KL Còn Lại");
        hashMap.put("Please input Description", "Chưa nhập Nội dung Chuyển tiền");

        hashMap.put("Doanh thu thuần", "Doanh thu thuần");
        hashMap.put("Lợi nhuận gộp", "Lợi nhuận gộp");
        hashMap.put("LN thuần từ HĐKD", "LN thuần từ HĐKD");
        hashMap.put("Lợi nhuận trước thuế", "Lợi nhuận trước thuế");
        hashMap.put("Lợi nhuận sau thuế", "Lợi nhuận sau thuế");
        hashMap.put("Tài sản ngắn hạn", "Tài sản ngắn hạn");
        hashMap.put("Tổng tài sản", "Tổng tài sản");
        hashMap.put("Nợ ngắn hạn", "Nợ ngắn hạn");
        hashMap.put("Nợ dài hạn", "Nợ dài hạn");
        hashMap.put("Vốn CSH", "Vốn CSH");
        hashMap.put("Vốn đầu tư CSH", "Vốn đầu tư CSH");
        hashMap.put("Cập nhật đến quý 2/2015", "Cập nhật đến quý 2/2015");
        hashMap.put("Please select Province", "Chưa chọn Tỉnh thành");
        hashMap.put("Please select Branch", "Chưa chọn Chi nhánh");
        hashMap.put("Lending Ratio:", "Tỷ lệ vay hiện tại (%):");

        hashMap.put("New Warning Rate:", "Tỷ lệ cảnh báo mới:");
        hashMap.put("New Margin Call Rate:", "Tỷ lệ xử lý mới (%):");

        hashMap.put("Tăng trưởng doanh thu", "Tăng trưởng doanh thu");
        hashMap.put("Tăng trưởng lợi nhuận thuần", "Tăng trưởng lợi nhuận thuần");
        hashMap.put("Tăng trưởng tổng tài sản", "Tăng trưởng tổng tài sản");
        hashMap.put("ROE", "ROE");
        hashMap.put("ROA", "ROA");
        hashMap.put("Chỉ tiêu đầu tư tự doanh", "Chỉ tiêu đầu tư tự doanh");
        hashMap.put("Khả năng thanh toán hiện hành", "Khả năng thanh toán hiện hành");
        hashMap.put("Nợ thanh toán GDCK/nguồn vốn", "Nợ thanh toán GDCK/nguồn vốn");
        hashMap.put("Khả năng thanh toán nhanh", "Khả năng thanh toán nhanh");
        hashMap.put("Trích dự phòng giảm giá CK", "Trích dự phòng giảm giá CK");
        hashMap.put("Tổng nợ/Vốn CSH", "Tổng nợ/Vốn CSH");
        hashMap.put("Đòn bẩy (Tổng TS/Vốn CSH)", "Đòn bẩy (Tổng TS/Vốn CSH)");
        hashMap.put("Tỷ lệ chi phí HĐKD CK", "Tỷ lệ chi phí HĐKD CK");
        hashMap.put("Success!", "Giao dịch Thành công!");
        hashMap.put("Incorrect Trading Password", "Sai Mật khẩu Giao dịch");
        hashMap.put("Account Name", "Tên người nhận");

        hashMap.put("Remaining credit line", "Hạn mức còn lại");
        hashMap.put("Loan amount:", "Số tiền vay");
        hashMap.put("Payment Amt. should be less than Remaining Loan Amt.", "Số tiền thanh toán không được vượt Dư nợ");
        hashMap.put("Please input payment amt.", "Chưa nhập Số tiền Thanh toán");
        hashMap.put("Quantity must be less than", "Số lượng phải nhỏ hơn");

        hashMap.put("Pending Settlement", "Tiền bán chờ TT");
        hashMap.put("Cash & Stock", "Tiền & Chứng Khoán");
        hashMap.put("Margin Loans", "Dư Nợ Ký Quỹ");
        hashMap.put("Total:", "Tổng:");

        hashMap.put("Restrict Stock", "Chứng khoán Hạn chế");
        hashMap.put("Open Qty", "SL Mở cửa");
        hashMap.put("Selling Qty", "Đang treo");
        hashMap.put("Available Qty", "SL Hiện tại");

        hashMap.put("Watchlist", "Bảng Giá");

        /* Stock Detail */
        hashMap.put("Giá trị vốn hóa thị trường", "Giá trị vốn hóa thị trường");
        hashMap.put("KLNY hiện tại", "KLNY hiện tại");
        hashMap.put("KLĐLH hiện tại", "KLĐLH hiện tại");
        hashMap.put("KLGD bq 30 ngày", "KLGD bq 30 ngày");
        hashMap.put("Giá cao nhất 52 tuần", "Giá cao nhất 52 tuần");
        hashMap.put("Giá thấp nhất 52 tuần", "Giá thấp nhất 52 tuần");
        hashMap.put("Tỷ lệ sở hữu nước ngoài", "Tỷ lệ sở hữu nước ngoài");
        hashMap.put("EPS*", "EPS*");
        hashMap.put("P/E*", "P/E*");
        hashMap.put("EPS điều chỉnh*", "EPS điều chỉnh*");
        hashMap.put("EPS(FPTS)**", "EPS(FPTS)**");
        hashMap.put("P/E(FPTS)**", "P/E(FPTS)**");

        hashMap.put("Doanh thu thuần", "Doanh thu thuần");
        hashMap.put("Lợi nhuận gộp", "Lợi nhuận gộp");
        hashMap.put("LN thuần từ HĐKD", "LN thuần từ HĐKD");
        hashMap.put("Lợi nhuận trước thuế", "Lợi nhuận trước thuế");
        hashMap.put("Lợi nhuận sau thuế", "Lợi nhuận sau thuế");
        hashMap.put("Tài sản ngắn hạn", "Tài sản ngắn hạn");
        hashMap.put("Tổng tài sản", "Tổng tài sản");
        hashMap.put("Nợ ngắn hạn", "Nợ ngắn hạn");
        hashMap.put("Nợ dài hạn", "Nợ dài hạn");
        hashMap.put("Vốn CSH", "Vốn CSH");
        hashMap.put("Vốn đầu tư CSH", "Vốn đầu tư CSH");
        hashMap.put("Cập nhật đến quý 2/2015", "Cập nhật đến quý 2/2015");

        hashMap.put("Thu nhập lãi thuần", "Thu nhập lãi thuần");
        hashMap.put("Thu nhập HĐKD thuần", "Thu nhập HĐKD thuần");
        hashMap.put("Thu nhập HĐKD trước dự phòng", "Thu nhập HĐKD trước dự phòng");
        hashMap.put("Lợi nhuận thuần", "Lợi nhuận thuần");
        hashMap.put("Tổng tài sản", "Tổng tài sản");
        hashMap.put("Cho vay khách hàng", "Cho vay khách hàng");
        hashMap.put("Tiền gửi khách hàng", "Tiền gửi khách hàng");
        hashMap.put("Vốn CSH", "Vốn CSH");
        hashMap.put("Cập nhật đến quý 2/2015", "Cập nhật đến quý 2/2015");

        hashMap.put("Doanh thu thuần", "Doanh thu thuần");
        hashMap.put("Lợi nhuận gộp", "Lợi nhuận gộp");
        hashMap.put("Lợi nhuận từ HĐKD", "Lợi nhuận từ HĐKD");
        hashMap.put("Lợi nhuận trước thuế", "Lợi nhuận trước thuế");
        hashMap.put("Lợi nhuận sau thuế", "Lợi nhuận sau thuế");
        hashMap.put("Tổng tài sản", "Tổng tài sản");
        hashMap.put("Tài sản ngắn hạn", "Tài sản ngắn hạn");
        hashMap.put("Nợ phải trả", "Nợ phải trả");
        hashMap.put("Nợ ngắn hạn", "Nợ ngắn hạn");
        hashMap.put("Nợ dài hạn", "Nợ dài hạn");
        hashMap.put("Vốn CSH", "Vốn CSH");
        hashMap.put("Vốn đầu tư CSH", "Vốn đầu tư CSH");
        hashMap.put("Cập nhật đến quý 1/2015", "Cập nhật đến quý 1/2015");

        hashMap.put("Doanh thu", "Doanh thu");
        hashMap.put("Lợi nhuận thuần", "Lợi nhuận thuần");
        hashMap.put("Tổng tài sản", "Tổng tài sản");
        hashMap.put("Vốn CSH", "Vốn CSH");
        hashMap.put("Cập nhật đến quý 2/2015", "Cập nhật đến quý 2/2015");

        hashMap.put("Tăng trưởng doanh thu", "Tăng trưởng doanh thu");
        hashMap.put("Tăng trưởng lợi nhuận thuần", "Tăng trưởng lợi nhuận thuần");
        hashMap.put("Tăng trưởng Tổng tài sản", "Tăng trưởng Tổng tài sản");
        hashMap.put("ROE (Lợi nhuận trên vốn chủ sở hữu)", "ROE (Lợi nhuận trên vốn chủ sở hữu)");
        hashMap.put("ROA", "ROA");
        hashMap.put("Khả năng thanh toán hiện hành", "Khả năng thanh toán hiện hành");
        hashMap.put("Khả năng thanh toán nhanh", "Khả năng thanh toán nhanh");
        hashMap.put("Tổng nợ/Vốn chủ sở hữu", "Tổng nợ/Vốn chủ sở hữu");
        hashMap.put("Tổng nợ/Tổng tài sản", "Tổng nợ/Tổng tài sản");
        hashMap.put("Cập nhật đến quý 2/2015", "Cập nhật đến quý 2/2015");
//        hashMap.put("Tiền Khác", "Tiền Khác");

        hashMap.put("Tăng trưởng tín dụng", "Tăng trưởng tín dụng");
        hashMap.put("Tăng trưởng tổng tài sản", "Tăng trưởng tổng tài sản");
        hashMap.put("Tăng trưởng huy động vốn", "Tăng trưởng huy động vốn");
        hashMap.put("ROE", "ROE");
        hashMap.put("ROA", "ROA");
        hashMap.put("Thu nhập lãi cận biên", "Thu nhập lãi cận biên");
        hashMap.put("Tỷ lệ an toàn vốn tối thiểu", "Tỷ lệ an toàn vốn tối thiểu");
        hashMap.put("Cập nhật đến quý 2/2015", "Cập nhật đến quý 2/2015");

        hashMap.put("Tăng trưởng doanh thu", "Tăng trưởng doanh thu");
        hashMap.put("Tăng trưởng lợi nhuận thuần", "Tăng trưởng lợi nhuận thuần");
        hashMap.put("Tăng trưởng tổng tài sản", "Tăng trưởng tổng tài sản");
        hashMap.put("ROE", "ROE");
        hashMap.put("ROA", "ROA");
        hashMap.put("Chỉ tiêu đầu tư tự doanh", "Chỉ tiêu đầu tư tự doanh");
        hashMap.put("Khả năng thanh toán hiện hành", "Khả năng thanh toán hiện hành");
        hashMap.put("Nợ thanh toán GDCK/nguồn vốn", "Nợ thanh toán GDCK/nguồn vốn");
        hashMap.put("Khả năng thanh toán nhanh", "Khả năng thanh toán nhanh");
        hashMap.put("Trích dự phòng giảm giá CK", "Trích dự phòng giảm giá CK");
        hashMap.put("Tổng nợ/Vốn CSH", "Tổng nợ/Vốn CSH");
        hashMap.put("Đòn bẩy (Tổng TS/Vốn CSH)", "Đòn bẩy (Tổng TS/Vốn CSH)");
        hashMap.put("Tỷ lệ chi phí HĐKD CK", "Tỷ lệ chi phí HĐKD CK");
        hashMap.put("Tổng nợ/Tổng tài sản", "Tổng nợ/Tổng tài sản");
        hashMap.put("Cập nhật đến quý 1/2015", "Cập nhật đến quý 1/2015");

        hashMap.put("Tổng DT phí BH/nguồn vốn", "Tổng DT phí BH/nguồn vốn");
        hashMap.put("DT phí BH thuần/nguồn vốn", "DT phí BH thuần/nguồn vốn");
        hashMap.put("Trợ vốn/nguồn vốn", "Trợ vốn/nguồn vốn");
        hashMap.put("Tỷ lệ bồi thường", "Tỷ lệ bồi thường");
        hashMap.put("Tỷ lệ chi phí HDKD", "Tỷ lệ chi phí HDKD");
        hashMap.put("Tỷ lệ kết hợp", "Tỷ lệ kết hợp");
        hashMap.put("Tỷ suất lợi nhuận đầu tư", "Tỷ suất lợi nhuận đầu tư");
        hashMap.put("Công nợ/tài sản thanh khoản", "Công nợ/tài sản thanh khoản");
        hashMap.put("Nợ phí/nguồn vốn", "Nợ phí/nguồn vốn");
        hashMap.put("Dự phòng bồi thường/phí BH", "Dự phòng bồi thường/phí BH");
        hashMap.put("Cập nhật đến quý 2/2015", "Cập nhật đến quý 2/2015");

        hashMap.put("Split order", "Tách lệnh");
        hashMap.put("Mrk.", "Giá");
        hashMap.put("B1", "M1");
        hashMap.put("B2", "M2");
        hashMap.put("B3", "M3");
        hashMap.put("S1", "B1");
        hashMap.put("S2", "B2");
        hashMap.put("S3", "B3");
        hashMap.put("Contract List", "Danh sách Hợp Đồng");
        hashMap.put("Mortgage Order", "Đặt lệnh Cầm cố");


        /// --- Update tu dien viet 23/2 ---///

        /// -- Doanh Nghiep thuong (Viet) ---///
        hashMap.put("Doanh thu bán hàng & dịch vụ", "Doanh thu bán hàng & dịch vụ");
        hashMap.put("Lợi nhuận gộp bán hàng & dịch vụ", "Lợi nhuận gộp bán hàng & dịch vụ");
        hashMap.put("Lợi nhuận thuần từ HĐKD", "Lợi nhuận thuần từ HĐKD");
        hashMap.put("Lợi nhuận (lỗ) kế toán trước thuế", "Lợi nhuận (lỗ) kế toán trước thuế");
        hashMap.put("Lợi nhuận (lỗ) sau thuế TNDN", "Lợi nhuận (lỗ) sau thuế TNDN");
        hashMap.put("Tài sản ngắn hạn", "Tài sản ngắn hạn");
        hashMap.put("Tổng tài sản", "Tổng tài sản");
        hashMap.put("Nợ ngắn hạn", "Nợ ngắn hạn");
        hashMap.put("Nợ dài hạn", "Nợ dài hạn");
        hashMap.put("Vốn CSH", "Vốn CSH");
        hashMap.put("Vốn đầu tư của CSH", "Vốn đầu tư của CSH");
        hashMap.put("Cập nhật đến quý 4/2016", "Cập nhật đến quý 4/2016");
        /// --- Ngan Hang Viet --- ///
        hashMap.put("Thu nhập lãi và thu nhập tương tự", "Thu nhập lãi và thu nhập tương tự");
        hashMap.put("Lãi/Lỗ thuần từ HĐDV", "Lãi/Lỗ thuần từ HĐDV");
        hashMap.put("LNT HĐKD trước CPDP RR Tín dụng", "LNT HĐKD trước CPDP RR Tín dụng");
        hashMap.put("Lợi nhuận sau thuế", "Lợi nhuận sau thuế");
        hashMap.put("Tổng tài sản", "Tổng tài sản");
        hashMap.put("Cho vay khách hàng", "Cho vay khách hàng");
        hashMap.put("Tiền gửi khách hàng", "Tiền gửi khách hàng");
        hashMap.put("Tổng vốn CSH", "Tổng vốn CSH");
        ///--- Cong ty chung khoan Viet --///
        hashMap.put("Doanh thu hoạt động", "Doanh thu hoạt động");
        hashMap.put("Chi phí hoạt động", "Chi phí hoạt động");
        hashMap.put("Kết quả hoạt động", "Kết quả hoạt động");
        hashMap.put("Lợi nhuận kế toán trước thuế", "Lợi nhuận kế toán trước thuế");
        hashMap.put("Lợi nhuận kế toán sau thuế", "Lợi nhuận kế toán sau thuế");
        hashMap.put("Tổng cộng tài sản", "Tổng cộng tài sản");
        hashMap.put("Tài sản ngắn hạn", "Tài sản ngắn hạn");
        hashMap.put("Nợ phải trả", "Nợ phải trả");
        hashMap.put("Nợ phải trả ngắn hạn", "Nợ phải trả ngắn hạn");
        hashMap.put("Nợ phải trả dài hạn", "Nợ phải trả dài hạn");
        hashMap.put("Vốn đầu tư CSH", "Vốn đầu tư CSH");
        hashMap.put("Vốn góp của CSH", "Vốn góp của CSH");

        /// --- Bao hiem viet ---///
        hashMap.put("Doanh thu thuần hoạt động kinh doanh bảo hiểm", "Doanh thu thuần HĐKD Bảo hiểm");
        hashMap.put("Lợi nhuận sau thuế TNDN", "Lợi nhuận sau thuế TNDN");
        hashMap.put("Tổng cộng tài sản", "Tổng cộng tài sản");
        hashMap.put("Vốn CSH", "Vốn CSH");

        /// --- Chung chi quy Viet ---///
        hashMap.put("Tổng tài sản", "Tổng tài sản");
        hashMap.put("Đầu tư chứng khoán", "Đầu tư chứng khoán");
        hashMap.put("Nguồn vốn CSH", "Nguồn vốn CSH");
        hashMap.put("Thu nhập từ HĐ đầu tư đã thực hiện", "Thu nhập từ HĐ đầu tư đã thực hiện");
        hashMap.put("KQHĐ ròng đã thực hiện trong kỳ", "KQHĐ ròng đã thực hiện trong kỳ");
        hashMap.put("Lợi nhuận trong năm", "Lợi nhuận trong năm");
    }

    public void putdataLangueAnh() {
        hashMap = new HashMap<>();
        hashMap.put("Limit balance", "Limit balance :");
        hashMap.put("Aggregate buying power", "Aggregate buying power :");
        hashMap.put("Choose your category", "Choose your category");
        hashMap.put("Choose category", "Choose your category please!");
        hashMap.put("Quantity should be more than 100","Quantity should be more than 100");
        hashMap.put("Cancel", "Cancel");
        hashMap.put("Network connection Error", "Network connection Error");
        hashMap.put("Quantity should be more than 0 and  must be lesser than 100", "Quantity should be more than 0 and  must be lesser than 100");
        hashMap.put("Quantity should be more than 10 and must be a multiple of 10", "Quantity should be more than 10 and must be a multiple of 10");
        hashMap.put("Quantity should be more than 100 and must be a multiple of 100", "Quantity should be more than 100 and must be a multiple of 100");
        hashMap.put("Margin Account Detail","Margin Account Detail");
        hashMap.put("Session Logout", "Session Logout");
        hashMap.put("Cancel Order Successful", "Cancel Order Successful");
        hashMap.put("Margin Account Details", "Margin Account Details");
        hashMap.put("Securities", "Securities");
        hashMap.put("Securities Symbol", "Securities Symbol");
        hashMap.put("Available", "Available");
        hashMap.put("Pending for Settlement", "Pending for Settlement");
        hashMap.put("Pending for Corporate Actions", "Pending for Corporate Actions");
        hashMap.put("MarketData Price", "MarketData Price");
        hashMap.put("Rate (Right)", "Rate (Right)");
        hashMap.put("Securities-leveraged buying power", "Securities-leveraged buying power");

        hashMap.put("Account Details", "Account Details");
        hashMap.put("Cash", "Cash");
        hashMap.put("Cash on hold", "Cash on hold");
        hashMap.put("Cash pending payment", "Cash pending payment");
        hashMap.put("Cash in transit", "Cash in transit");
        hashMap.put("Basic buying power", "Basic buying power :");
        hashMap.put("Total credit limit", "Total credit limit");
        hashMap.put("Outstanding debt", "Outstanding debt");
        hashMap.put("Accumulated interest", "Accumulated interest");
        hashMap.put("Current R", "Current R");
        hashMap.put("Amount Called", "Amount Called");
        hashMap.put("Rxl", "Rxl");

        hashMap.put("Cashbuy:", "Order value:");
        hashMap.put("The amount of the amount of a balance", "The amount of the amount of a balance");
        hashMap.put("Special characters name", "Name account can not have some Special characters!");
        hashMap.put("Please input name", "Please input name account!");
        hashMap.put("Special characters", "Your content can not have some Special characters!");
        hashMap.put("Updated to:", "Updated to:");
        hashMap.put("Not response", "Have an unknown error");
        hashMap.put("Sức mua CK còn lại:", "Buying Power from stocks:");
        hashMap.put("Other Money:", "Other Money:");
        hashMap.put("Pending Order", "Pending Order");
        hashMap.put("Today's Orders", "Today's Orders");
        hashMap.put("Please update your app !", "Please update your app !");
        hashMap.put("Current version is out of date. Please upgrade to new version!", "Current version is out of date. Please upgrade to new version!");
        hashMap.put("Delete Watchlist", "Delete Watchlist");
        hashMap.put("MarketData is opened", "MarketData is opened");
        hashMap.put("The quantity each split order must be bigger than 1000", "The quantity each split order must be bigger than 1000");
        hashMap.put("Skip", "Skip");
        hashMap.put("Symbol Search", "Symbol Search");
        hashMap.put("Quantity should be more than 999", "Quantity should be more than 999");
        hashMap.put("News", "News");
        hashMap.put("CASH", "CASH");
        hashMap.put("MARGIN", "MARGIN");
        hashMap.put("P/L", "P/L");
        hashMap.put("The Cash Receive must be less than", "The Cash Receive must be less than");
        hashMap.put("Normal order quantity should be less than 500.000 (HOSE stock). You should split order.", "Normal order quantity should be less than 500.000 (HOSE stock). You should split order.");
        hashMap.put("Contract List", "Contract List");
        hashMap.put("Mortgage Order", "Mortgage Order");
        hashMap.put("Add WatchList Name", "Add WatchList Name");
        hashMap.put("Please input Account", "Please input Account");
        hashMap.put("January", "January");
        hashMap.put("February", "February");
        hashMap.put("March", "March");
        hashMap.put("April", "April");
        hashMap.put("May", "May");
        hashMap.put("June", "June");
        hashMap.put("July", "July");
        hashMap.put("August", "August");
        hashMap.put("September", "September");
        hashMap.put("October", "October");
        hashMap.put("November", "November");
        hashMap.put("December", "December");
        hashMap.put("tháng 1", "January");
        hashMap.put("tháng 2", "February");
        hashMap.put("tháng 3", "March");
        hashMap.put("tháng 4", "April");
        hashMap.put("tháng 5", "May");
        hashMap.put("tháng 6", "June");
        hashMap.put("tháng 7", "July");
        hashMap.put("tháng 8", "August");
        hashMap.put("tháng 9", "September");
        hashMap.put("tháng 10", "October");
        hashMap.put("tháng 11", "November");
        hashMap.put("tháng 12", "December");
        hashMap.put("tháng 12", "December");

        //url
        hashMap.put("+/-", "+/-");
        hashMap.put("P.B3", "P.B3");
        hashMap.put("Q.B3", "Q.B3");
        hashMap.put("P.B2", "P.B2");
        hashMap.put("Q.B2", "Q.B2");
        hashMap.put("P.B1", "P.B1");
        hashMap.put("Q.B1", "Q.B1");

        hashMap.put("P.S1", "P.S1");
        hashMap.put("Q.S1", "Q.S1");
        hashMap.put("P.S2", "P.S2");
        hashMap.put("Q.S2", "Q.S2");
        hashMap.put("P.S3", "P.S3");
        hashMap.put("Q.S3", "Q.S3");
        hashMap.put("Switch account", "Switch account");
        hashMap.put("There is no information of indice", "There is no information of indice");
        hashMap.put("was setted as default Watchlist", "was setted as default Watchlist");
        hashMap.put("newshomee", "newshomee");
        hashMap.put("eventshomee", "eventshomee");
        hashMap.put("Incorrect Trading Password", "Incorrect Trading Password");
        hashMap.put("Ezmargin Sell", "Ezmargin Sell");
        hashMap.put("Order History", "Order History");
        hashMap.put("Content", "Content");
        hashMap.put("Amount", "Amount");
        hashMap.put("Renew", "Renew");
        hashMap.put("Time", "Time");
        hashMap.put("Rate", "Rate");
        hashMap.put("Order Type", "Order Type");
        hashMap.put("Status", "Status");
        hashMap.put("Product Type", "Product Type");
        hashMap.put("Exchange", "Exchange");
        hashMap.put("Order No.", "Order No.");
        hashMap.put("Buy/Sell", "Buy/Sell");
        hashMap.put("Remain Qty", "Remain Qty");
        hashMap.put("New Warning Rate:", "New Warning Rate:");
        hashMap.put("New Margin Call Rate:", "New Margin Call Rate(%):");
        hashMap.put("No. of days:", "No. of days:");

        hashMap.put("Order List", "Order List");
        hashMap.put("Select Template", "Select Template");
        hashMap.put("Bene.'s Account not exist", "Bene.'s Account not exist");
        hashMap.put("Split order", "Split order");

        hashMap.put("Please select Branch", "Please select Branch");

        hashMap.put("Match Price", "Match Price");
        hashMap.put("Price must be a multiple of", "Price must be a multiple of");
        hashMap.put("Contract No", "Contract No");
        hashMap.put("Home", "Home");
        hashMap.put("Favorites", "Favorites");
        hashMap.put("Features", "Features");
        hashMap.put("Member Area", "Member Area");
        hashMap.put("Setting", "Setting");
        hashMap.put("Total Vol", "Total Vol");
        hashMap.put("Dashboard", "Dashboard");
        hashMap.put("Pay Amount:", "Pay Amount:");
        hashMap.put("Rate (%/day):", "Rate (%/day):");
        hashMap.put("Member", "Member");
        hashMap.put("Interest:", "Interest:");
        hashMap.put("Watchlist", "Watchlist");
        hashMap.put("Fee:", "Fee:");
        hashMap.put("Fee", "Fee");
        hashMap.put("Events", "Events");
        hashMap.put("MarketData Overview", "MarketData Overview");
        hashMap.put("Headlines", "Headlines");
        hashMap.put("Watch List", "Watch List");
        hashMap.put("World Indexes", "World Indexes");
        hashMap.put("Order Type:", "Order Type:");
        hashMap.put("Please input Amount", "Please input Amount");
        hashMap.put("Please input Description", "Please input Description");

        hashMap.put("Place Orders", "Place Orders");
        hashMap.put("Money Transfer", "Money Transfer");
        hashMap.put("Sell Oddlot", "Sell Oddlot");
        hashMap.put("Advance Report", "Advance Report");
        hashMap.put("Margin", "Margin");
        hashMap.put("Asset Report", "Asset Report");

        hashMap.put("Language", "Language");
        hashMap.put("Remember Account", "Remember Account");
        ;

        hashMap.put("Indices", "Indices");
        hashMap.put("Last", "Last");
        hashMap.put("Last ", "Last ");
        hashMap.put("Change", "Change");
        hashMap.put("Volume", "Volume");
        hashMap.put("Value", "Value");
        hashMap.put("Symbol", "Symbol");

        hashMap.put("MarketData is opening", "MarketData is opening");
        hashMap.put("MarketData was closed", "MarketData was closed");
        hashMap.put("Breaking time", "Breaking time");

        hashMap.put("Quantity should be less than 999.999", "Quantity should be less than 999.999");

        hashMap.put("is not in the Margin stock list", "is not in the Margin stock list");
        hashMap.put("Account", "Account");
        hashMap.put("Indexes", "Indexes");
        hashMap.put("bil", "bil");
        hashMap.put("Detail", "Detail");
        hashMap.put("Chart", "Chart");
        hashMap.put("Top Gainers", "Top Gainers");
        hashMap.put("Top Losers", "Top Losers");
        hashMap.put("Most Active", "Most Active");
        hashMap.put("Search", "Search");
        hashMap.put("Vol", "Vol");
        hashMap.put("Val", "Val");
        hashMap.put("Qty", "Qty");
        hashMap.put("Up/Down stocks", "Up/Down stocks");
        hashMap.put("Putthrough", "Putthrough");

        hashMap.put("Open", "Open");
        hashMap.put("Close", "Close");
        hashMap.put("High", "High");
        hashMap.put("Low", "Low");
        hashMap.put("Forei.Buy", "Forei.Buy");
        hashMap.put("Held for buying orders:", "Held for buying orders:");
        hashMap.put("Other Money:", "Other Money:");
        hashMap.put("Forei.Sell", "Forei.Sell");

        hashMap.put("Get Quotes", "Get Quotes");
        hashMap.put("Ceil Price", "Ceil Price");
        hashMap.put("Floor Price", "Floor Price");
        hashMap.put("Ref Price", "Ref Price");
        hashMap.put("Buy Price ", "Buy Price");
        hashMap.put("Buy Quantity", "Buy Quantity");
        hashMap.put("Sell Price", "Sell Price");
        hashMap.put("Sell Quantity", "Sell Quantity");
        hashMap.put("Match", "Match");

        hashMap.put("MarketData News", "MarketData News");
        hashMap.put("Finance & Banking News", "Finance & Banking News");
        hashMap.put("Real Estate News", "Real Estate News");
        hashMap.put("Commodity News", "Commodity News");
        hashMap.put("Economy News", "Economy News");
        hashMap.put("World News", "World News");
        hashMap.put("FPTS News", "FPTS News");

        hashMap.put("Please enter your account", "Please enter your account");
        hashMap.put("Please enter your password", "Please enter your password");
        hashMap.put("WatchList must have at least one company", "WatchList must have at least one company");
        hashMap.put("Login", "Login");
        hashMap.put("Logout", "Logout");

        hashMap.put("Logged out", "Logged out");
        hashMap.put("Exit", "Exit");
        hashMap.put("Login with other account", "Login with other account");
        hashMap.put("Account", "Account");
        hashMap.put("Password", "Password");
        hashMap.put("Intraday Trading Result", "Intraday Trading Result");

        hashMap.put("Buy", "Buy");
        hashMap.put("Sell", "Sell");
        hashMap.put("Normal Stock", "Normal Stock");
        hashMap.put("Margin Stock", "Margin Stock");
        hashMap.put("Sell", "Sell");
        hashMap.put("Cash", "Cash");
        hashMap.put("Margin", "Margin");
        hashMap.put("Available Cash:", "Available Cash");
        hashMap.put("Available Stock:", "Available Stock");
        hashMap.put("Available Stock", "Available Stock");
        hashMap.put("New Interest Rate (%/day):", "New Interest Rate (%/day):");
        hashMap.put("Rate:", "Rate:");
        hashMap.put("Cash:", "Cash");
        hashMap.put("Ký Quỹ:", "Ký Quỹ");
        hashMap.put("Symbol:", "Symbol:");
        hashMap.put("Symbol", "Symbol");
        hashMap.put("Exchange:", "Exchange");
        hashMap.put("Renew", "Renew");
        hashMap.put("Side:", "Side");
        hashMap.put("Type:", "Type");
        hashMap.put("Quantity:", "Quantity");
        hashMap.put("Term:", "Term");
        hashMap.put("Price:", "Price :");
        hashMap.put("Extendable", "Extendable");
        hashMap.put("Password:", "Password:");
        hashMap.put("Quantity", "Quantity");
        hashMap.put("Price", "Price");
        hashMap.put("Expriry Date:", "Expriry Date:");
        hashMap.put("Trading Password", "Trading Password");
        hashMap.put("Confirm Buy", "Confirm Buy");
        hashMap.put("Confirm Sell", "Confirm Sell");

        hashMap.put("Quantity must be a multiple of 100", "Quantity must be a multiple of 100");
        hashMap.put("Price must be a multiple of 100", "Price must be a multiple of 100");
        hashMap.put("Price must be a multiple of 10", "Price must be a multiple of 10");
        hashMap.put("Price must be a multiple of 1", "Price must be a multiple of 1");
        hashMap.put("The price must be a multiple of", "The price must be a multiple of");
        hashMap.put("Price must be between", "Price must be between");
        hashMap.put("Quantity must be less than 500.000", "Quantity must be less than 500.000");
        hashMap.put("Quantity must be a multiple of 10", "Quantity must be a multiple of 10");
        hashMap.put("Symbol does not exist", "Symbol does not exist");
        hashMap.put("The quantity should be lesser than 999.999", "The quantity should be lesser than 999.999");
        hashMap.put("Quantity should be more than 0", "Quantity should be more than 0");
        hashMap.put("Price should be less than 999.999.999", "Price should be less than 999.999.999");
        hashMap.put("Price should be more than 0", "The price should be more than 0");
        hashMap.put("Please enter Symbol", "Please enter Symbol");
        hashMap.put("Please enter Quantity", "Please enter Quantity");
        hashMap.put("Please enter Price", "Please enter Price");
        hashMap.put("Please enter Trading Password", "Please enter Trading Password");
        hashMap.put("Your trading password is incorrect", "Your trading password is incorrect");
        hashMap.put("Cash balance is not enough", "Cash balance is not enough");
        hashMap.put("Stock balance is not enough", "Stock balance is not enough");
        hashMap.put("cannot buy Margin", "cannot buy Margin");

        hashMap.put("Amount:", "Amount");
        hashMap.put("New Expriry Date:", "New Expriry Date:");
        hashMap.put("Account:", "Account:");
        hashMap.put("Name:", "Name:");
        hashMap.put("Bank:", "Bank:");
        hashMap.put("Province:", "Province:");
        hashMap.put("Branch:", "Branch:");
        hashMap.put("Fee:", "Fee:");
        hashMap.put("Select Template", "Select Template");
        hashMap.put("Select Bank", "Select Bank");
        hashMap.put("Select Province", "Select Province");
        hashMap.put("Select Branch", "Select Branch");
        hashMap.put("Transfer Description", "Transfer Description");
        hashMap.put("Confirm", "Confirm");
        hashMap.put("Transfer History", "Transfer History");

        hashMap.put("Mortgage", "Mortgage");
        hashMap.put("Payment", "Payment");
        hashMap.put("Extend", "Extend");
        hashMap.put("Exit", "Exit");
        hashMap.put("Cash Total:", "Cash Total");
        hashMap.put("Cash Receive:", "Cash Receive:");

        hashMap.put("Contract:", "Contract:");
        hashMap.put("Contract", "Contract");
        hashMap.put("From Date", "From Date");
        hashMap.put("To Date", "To Date");
        hashMap.put("Detail", "Detail");
        hashMap.put("Cancel/Modify Order", "Cancel/Modify Order");

        hashMap.put("Pay Date:", "Pay Date:");
        hashMap.put("Contract Date:", "Contract Date:");
        hashMap.put("Contract Date", "Contract Date");
        hashMap.put("Date Count:", "Date Count:");
        hashMap.put("Cur. Mar Amount:", "Cur. Mar Amount:");
        hashMap.put("Cur. Mor Amount:", "Cur. Mor Amount:");
        hashMap.put("Pay Amount:", "Pay Amount");
        hashMap.put("Charge Rate:", "Charge Rate:");
        hashMap.put("Charge Amount:", "Charge Amount:");
        hashMap.put("Total Payment:", "Total Payment:");
        hashMap.put("Total", "Total");
        hashMap.put("New Qty:", "New Qty:");
        hashMap.put("New Price:", "New Price:");
        hashMap.put("Change Qty:", "Change Qty:");
        hashMap.put("Asset Report", "Asset Report");
        hashMap.put("Stock Balance", "Stock Balance");
        hashMap.put("Cash Balance", "Cash Balance");
        hashMap.put("Stock", "Stock");
        hashMap.put("Cash & Stock", "Cash & Stock");
        hashMap.put("Margin Amount", "Margin Amount");
        hashMap.put("Total:", "Total:");

        hashMap.put("BANK", "BANK");
        hashMap.put("Amount:", "Amount");
        hashMap.put("Account:", "Account:");
        hashMap.put("Name:", "Name:");
        hashMap.put("Bank:", "Bank:");
        hashMap.put("Province:", "Province:");
        hashMap.put("Account Name", "Account Name");
        hashMap.put("Branch:", "Branch:");
        hashMap.put("Estimated Fee:", "Estimated Fee");
        hashMap.put("Select Template", "Select Template");
        hashMap.put("Select Bank", "Select Bank");
        hashMap.put("Select Province", "Select Province");
        hashMap.put("Select Branch", "Select Branch");
        hashMap.put("Transfer Description", "Transfer Description");
        hashMap.put("Date", "Date");

        hashMap.put("Avg.Price", "Avg.Price");
        hashMap.put("Mkt.Price", "Mkt.Price");
        hashMap.put("Pending", "Pending");
        hashMap.put("Repay", "Repay");

        hashMap.put("Restrict Stock", "Restrict Stock");
        hashMap.put("Open Qty", "Open Qty");
        hashMap.put("Pending Qty", "Pending Qty");
        hashMap.put("Available Qty", "Available Qty");
        hashMap.put("Sellable", "Sellable");
        hashMap.put("Cash Balance:", "Cash Balance");
        hashMap.put("Available Cash:", "Available Cash");
        hashMap.put("Advance Amount:", "Advance Amount:");
        hashMap.put("Cash Being Transferred:", "Cash Being Transferred:");
        hashMap.put("Pending Buy Orders:", "Pending Buy Orders:");
        hashMap.put("Provisional Fee:", "Provisional Fee:");
        hashMap.put("Available Balance:", "Available Balance:");

        hashMap.put("Sell Oddlot History", "Sell Oddlot History");
        hashMap.put("Expire Date:", "Expire Date:");
        hashMap.put("New Contract Date:", "New Contract Date:");
        hashMap.put("New Expire Date:", "New Expire Date:");
        hashMap.put("Mar Amount:", "Mar Amount:");
        hashMap.put("Mor Amount:", "Mor Amount:");
        hashMap.put("New Charge Rate:", "New Charge Rate:");
        hashMap.put("The quantity must be lesser than", "The quantity must be lesser than");

        hashMap.put("Please enter Cash To Transfer", "Please enter Cash To Transfer");
        hashMap.put("Please enter Receiver Account", "Please enter Receiver Account");
        hashMap.put("Please enter Receiver Name", "Please enter Receiver Name");
        hashMap.put("Please enter Transfer Description", "Please enter Transfer Description");
        hashMap.put("Please select Bank", "Please select Bank");
        hashMap.put("Please select Province", "Please select Province");
        hashMap.put("Please select Branch", "Please select Branch");
        hashMap.put("Input invalid number", "Input invalid number");
        hashMap.put("Receiver Account does not exsit", "Receiver Account does not exsit");
        hashMap.put("Select Account To Transfer", "Select Account To Transfer");
        hashMap.put("Please Select Account To Transfer", "Please Select Account To Transfer");

        hashMap.put("Please select Date From", "Please select Date From");
        hashMap.put("Please select Date To", "Please select Date To");

        hashMap.put("Price, Quantity unchanged", "Price, Quantity unchanged");
        hashMap.put("Cancel Transfer Successfully", "Cancel Transfer Successfully");

        hashMap.put("Cancel Order", "Cancel Order");
        hashMap.put("Modify Order", "Modify Order");
        hashMap.put("Add Watch List", "Add Watch List");
        hashMap.put("Delete", "Delete");
        hashMap.put("Back", "Back");
        hashMap.put("Quantity each Order:", "Quantity each Order:");
        hashMap.put("Not enough stock balance", "Not enough stock balance");

        hashMap.put("Pay amount must be smaller than current Mar/Mor amount", "Pay amount must be smaller than current Mar/Mor amount");
        hashMap.put("Please enter Pay Amount", "Please enter Pay Amount");

        hashMap.put("Overview", "Overview");
        hashMap.put("Foreign Ownership", "Foreign Ownership");
        hashMap.put("Company News", "Company News");
        hashMap.put("Finance Overview", "Finance Overview");
        hashMap.put("Financial Figures", "Financial Figures");
        hashMap.put("Chart", "Chart");
        hashMap.put("Key FS Items", "Key FS Items");
        hashMap.put("Financial Ratios", "Financial Ratios");
        hashMap.put("Foreign-owned Ratio (%):", "Foreign-owned Ratio (%):");
        hashMap.put("Please select Bank", "Please select Bank");
        hashMap.put("Please select Province", "Please select Province");
        hashMap.put("Remaining Loan Amt:", "Remaining Loan Amt:");

        hashMap.put("Last", "Last");
        hashMap.put("Change", "Change");
        hashMap.put("Volume", "Volume");
        hashMap.put("Ceil", "Ceil");
        hashMap.put("Ref", "Ref");
        hashMap.put("Floor", "Floor");
        hashMap.put("High", "High");
        hashMap.put("Low", "Low");
        hashMap.put("Foreign Buy:", "Foreign Buy:");
        hashMap.put("Foreign Sell:", "Foreign Sell:");

        hashMap.put("Matching:", "Matching:");
        hashMap.put("Putthrough:", "Putthrough:");
        hashMap.put("Vol:", "Vol:");
        hashMap.put("Value:", "Value:");

        hashMap.put("Total Room:", "Total Room:");
        hashMap.put("Current Room:", "Current Room:");
        hashMap.put("Remain Room:", "Remain Room:");
        hashMap.put("Ratios (%):", "Ratios (%):");

        hashMap.put("Modify Order Successful", "Modify Order Successful");
        hashMap.put("WatchList Name", "WatchList Name");
        hashMap.put("Please input WatchList Name", "Please input WatchList Name");
        hashMap.put("Symbol is already in Quotes", "Symbol is already in Quotes");
        hashMap.put("Request has been executed successfully!", "Request has been executed successfully!");

        hashMap.put("Stock is not enough to mortgage", "Stock is not enough to mortgage");
        hashMap.put("Lending Ratio:", "Lending Ratio (%):");
        hashMap.put("Success!", "Success!");

        hashMap.put("Doanh thu thuần", "Revenue");
        hashMap.put("Lợi nhuận gộp", "Gross profit/ (loss)");
        hashMap.put("LN thuần từ HĐKD", "Net operating profit/ (Loss)");
        hashMap.put("Lợi nhuận trước thuế", "Net accounting profit/ (loss) before tax");
        hashMap.put("Lợi nhuận sau thuế", "Profit/ (loss) after tax");
        hashMap.put("Tài sản ngắn hạn", "Current assets");
        hashMap.put("Tổng tài sản", "Total assets");
        hashMap.put("Nợ ngắn hạn", "Current liabilities");
        hashMap.put("Nợ dài hạn", "Non-current liabilities");
        hashMap.put("Vốn CSH", "Owner's equity");
        hashMap.put("Vốn đầu tư CSH", "Contributed capital");
        hashMap.put("Cập nhật đến quý 2/2015", "Updated to 2/2015");

        hashMap.put("Tăng trưởng doanh thu", "Revenue growth");
        hashMap.put("Tăng trưởng lợi nhuận thuần", "Net profit growth");
        hashMap.put("Tăng trưởng tổng tài sản", "Total assets growth");
        hashMap.put("ROE", "ROE");
        hashMap.put("ROA", "ROA");
        hashMap.put("Chỉ tiêu đầu tư tự doanh", "Proprietary Performance");
        hashMap.put("Khả năng thanh toán hiện hành", "Current ratio");
        hashMap.put("Nợ thanh toán GDCK/nguồn vốn", "Receivables from investors/owner's equity");
        hashMap.put("Khả năng thanh toán nhanh", "Quick ratio");
        hashMap.put("Trích dự phòng giảm giá CK", "Provision for diminution in the value of securities to equity ratio");
        hashMap.put("Tổng nợ/Vốn CSH", "Total liabilities/Owner's equity");
        hashMap.put("Đòn bẩy (Tổng TS/Vốn CSH)", "Leverage ratio (Total assets/sharedholds' equity)");
        hashMap.put("Tỷ lệ chi phí HĐKD CK", "Operating expenses/Net operating revenue");

        hashMap.put("Remaining credit line", "Remaining credit line");
        hashMap.put("Loan amount:", "Loan amount");
        hashMap.put("Payment Amt. should be less than Remaining Loan Amt.", "Payment Amt. should be less than Remaining Loan Amt.");
        hashMap.put("Please input payment amt.", "Please input payment amt.");
        hashMap.put("Quantity must be less than", "Quantity must be less than");

        hashMap.put("Pending Settlement", "Pending Settlement");
        hashMap.put("Cash & Stock", "Cash & Stock");
        hashMap.put("Margin Loans", "Margin Loans");
        hashMap.put("Total:", "Total:");

        hashMap.put("Restrict Stock", "Restrict Stock");
        hashMap.put("Open Qty", "Open Qty");
        hashMap.put("Selling Qty", "Selling Qty");
        hashMap.put("Available Qty", "Available Qty");

        /* Stock Detail */
        hashMap.put("Giá trị vốn hóa thị trường", "MarketData Capitalisation");
        hashMap.put("KLNY hiện tại", "Current Listing Shares");
        hashMap.put("KLĐLH hiện tại", "Current Outstanding Shares");
        hashMap.put("KLGD bq 30 ngày", "30 days average vol.");
        hashMap.put("Giá cao nhất 52 tuần", "52 Weeks High");
        hashMap.put("Giá thấp nhất 52 tuần", "52 Weeks Low");
        hashMap.put("Tỷ lệ sở hữu nước ngoài", "Foreign Ownership");
        hashMap.put("EPS*", "EPS*");
        hashMap.put("P/E*", "P/E*");
        hashMap.put("EPS điều chỉnh*", "Adjusted EPS*");
        hashMap.put("EPS(FPTS)**", "EPS(FPTS)**");
        hashMap.put("P/E(FPTS)**", "P/E(FPTS)**");

        hashMap.put("Doanh thu thuần", "Revenue");
        hashMap.put("Lợi nhuận gộp", "Gross profit/ (loss)");
        hashMap.put("LN thuần từ HĐKD", "Net operating profit/ (Loss)");
        hashMap.put("Lợi nhuận trước thuế", "Net accounting profit/ (loss) before tax");
        hashMap.put("Lợi nhuận sau thuế", "Profit/ (loss) after tax");
        hashMap.put("Tài sản ngắn hạn", "Current assets");
        hashMap.put("Tổng tài sản", "Total assets");
        hashMap.put("Nợ ngắn hạn", "Current liabilities");
        hashMap.put("Nợ dài hạn", "Non-current liabilities");
        hashMap.put("Vốn CSH", "Owner's equity");
        hashMap.put("Vốn đầu tư CSH", "Contributed capital");
        hashMap.put("Cập nhật đến quý 2/2015", "Updated to 2/2015");

        hashMap.put("Thu nhập lãi thuần", "Net interest and similar income");
        hashMap.put("Thu nhập HĐKD thuần", "Net gain/(loss) from fees, commissions");
        hashMap.put("Thu nhập HĐKD trước dự phòng", "Net operating profit before provision");
        hashMap.put("Lợi nhuận thuần", "Profit/ (loss) after tax");
        hashMap.put("Tổng tài sản", "Total assets");
        hashMap.put("Cho vay khách hàng", "Loans to customers");
        hashMap.put("Tiền gửi khách hàng", "Deposits from customers");
        hashMap.put("Vốn CSH", "Owner's equity");
        hashMap.put("Cập nhật đến quý 4/2015", "Updated to 4/2015");

//        hashMap.put("Tiền Khác", "Other Money:");

        hashMap.put("Doanh thu thuần", "Net operating revenue");
        hashMap.put("Lợi nhuận gộp", "Gross operating profit");
        hashMap.put("Lợi nhuận từ HĐKD", "Net operating profit/ (Loss)");
        hashMap.put("Lợi nhuận trước thuế", "Net accounting profit/ (loss) before tax");
        hashMap.put("Lợi nhuận sau thuế", "Profit/ (loss) after tax");
        hashMap.put("Tổng tài sản", "Total assets");
        hashMap.put("Tài sản ngắn hạn", "Current assets");
        hashMap.put("Nợ phải trả", "Liabilities");
        hashMap.put("Nợ ngắn hạn", "Current liabilities");
        hashMap.put("Nợ dài hạn", "Non-current liabilities");
        hashMap.put("Vốn CSH", "Owner's equity");
        hashMap.put("Vốn đầu tư CSH", "Contributed capital");
        hashMap.put("Cập nhật đến quý 1/2015", "Updated to 1/2015");

        hashMap.put("Doanh thu", "Revenue");
        hashMap.put("Lợi nhuận thuần", "Profit/ (loss) after tax");
        hashMap.put("Tổng tài sản", "Total assets");
        hashMap.put("Vốn CSH", "Owner's equity");
        hashMap.put("Cập nhật đến quý 4/2015", "Updated to 4/2015");

        hashMap.put("Tăng trưởng doanh thu", "Revenue growth");
        hashMap.put("Tăng trưởng lợi nhuận thuần", "Net profit growth");
        hashMap.put("Tăng trưởng Tổng tài sản", "Total assets growth");
        hashMap.put("ROE (Lợi nhuận trên vốn chủ sở hữu)", "ROE");
        hashMap.put("ROA", "ROA");
        hashMap.put("Khả năng thanh toán hiện hành", "Current ratio");
        hashMap.put("Khả năng thanh toán nhanh", "Quick ratio");
        hashMap.put("Tổng nợ/Vốn chủ sở hữu", "Total liabilities/Owner's equity");
        hashMap.put("Tổng nợ/Tổng tài sản", "Total liabilities/Total assets");
        hashMap.put("Cập nhật đến quý 2/2015", "Updated to 2/2015");

        hashMap.put("Tăng trưởng tín dụng", "Credit Growth");
        hashMap.put("Tăng trưởng tổng tài sản", "Total assets growth");
        hashMap.put("Tăng trưởng huy động vốn", "Mobilized Growth");
        hashMap.put("ROE", "ROE");
        hashMap.put("ROA", "ROA");
        hashMap.put("Thu nhập lãi cận biên", "Net Interest Margin");
        hashMap.put("Tỷ lệ an toàn vốn tối thiểu", "Capital Adequacy Ratio");
        hashMap.put("Cập nhật đến quý 2/2015", "Updated to 2/2015");

        hashMap.put("Tăng trưởng doanh thu", "Revenue growth");
        hashMap.put("Tăng trưởng lợi nhuận thuần", "Net profit growth");
        hashMap.put("Tăng trưởng tổng tài sản", "Total assets growth");
        hashMap.put("ROE", "ROE");
        hashMap.put("ROA", "ROA");
        hashMap.put("Chỉ tiêu đầu tư tự doanh", "Proprietary Performance");
        hashMap.put("Khả năng thanh toán hiện hành", "Current ratio");
        hashMap.put("Nợ thanh toán GDCK/nguồn vốn", "Receivables from investors/owner's equity");
        hashMap.put("Khả năng thanh toán nhanh", "Quick ratio");
        hashMap.put("Trích dự phòng giảm giá CK", "Provision for diminution in the value of securities to equity ratio");
        hashMap.put("Tổng nợ/Vốn CSH", "Total liabilities/Owner's equity");
        hashMap.put("Đòn bẩy (Tổng TS/Vốn CSH)", "Leverage ratio (Total assets/sharedholds' equity)");
        hashMap.put("Tỷ lệ chi phí HĐKD CK", "Operating expenses/Net operating revenue");
        hashMap.put("Tổng nợ/Tổng tài sản", "Total liabilities/Total assets");
        hashMap.put("Cập nhật đến quý 1/2015", "Updated to 1/2015");

        hashMap.put("Tổng DT phí BH/nguồn vốn", "Gross premium/ Equity and funds");
        hashMap.put("DT phí BH thuần/nguồn vốn", "Net premium/ Equity and funds");
        hashMap.put("Trợ vốn/nguồn vốn", "Subsidy ratio");
        hashMap.put("Tỷ lệ bồi thường", "Claim ratio");
        hashMap.put("Tỷ lệ chi phí HDKD", "Insurance expense ratio");
        hashMap.put("Tỷ lệ kết hợp", "Combination ratio");
        hashMap.put("Tỷ suất lợi nhuận đầu tư", "Profit from investment ratio");
        hashMap.put("Công nợ/tài sản thanh khoản", "Liability/ Liquid assets");
        hashMap.put("Nợ phí/nguồn vốn", "Free receivables");
        hashMap.put("Dự phòng bồi thường/phí BH", "Reserve/ Net premium");
        hashMap.put("Cập nhật đến quý 2/2015", "Updated to 2/2015");

        hashMap.put("Mrk.", "Mrk.");
        hashMap.put("B1", "B1");
        hashMap.put("B2", "B2");
        hashMap.put("B3", "B3");
        hashMap.put("S1", "S1");
        hashMap.put("S2", "S2");
        hashMap.put("S3", "S3");
        hashMap.put("SELL", "SELL");
        hashMap.put("BUY", "BUY");

        /// --- Update tu dien Anh 23/2 ---///
        /// --- Doanh nghiep thuong Anh --- ///
        hashMap.put("Doanh thu bán hàng & dịch vụ", "Revenue");
        hashMap.put("Lợi nhuận gộp bán hàng & dịch vụ", "Gross profit/ (loss)");
        hashMap.put("Lợi nhuận thuần từ HĐKD", "Net operating profit/ (loss)");
        hashMap.put("Lợi nhuận (lỗ) kế toán trước thuế", "Net accounting profit/ (loss) before tax");
        hashMap.put("Lợi nhuận (lỗ) sau thuế TNDN", "Profit/ (loss) after tax");
        hashMap.put("Tài sản ngắn hạn", "Profit/ (loss) after tax");
        hashMap.put("Tổng tài sản", "Total assets");
        hashMap.put("Nợ ngắn hạn", "Current liabilities");
        hashMap.put("Nợ dài hạn", "Non-current liabilities");
        hashMap.put("Vốn CSH", "Owners' equity");
        hashMap.put("Vốn đầu tư của CSH", "Contributed capital");
        hashMap.put("Cập nhật đến quý 4/2016", "Updated to 4/2016");
        /// --- Ngan hang Anh ---///
        hashMap.put("Thu nhập lãi và thu nhập tương tự", "Interest income and similar income");
        hashMap.put("Lãi/Lỗ thuần từ HĐDV", "Net gain/(loss) from fees, commissions");
        hashMap.put("LNT HĐKD trước CPDP RR Tín dụng", "Net operating profit before PCL");
        hashMap.put("Lợi nhuận sau thuế", "Net profit after tax");
        hashMap.put("Tổng tài sản", "Total assets");
        hashMap.put("Cho vay khách hàng", "Loans to customers");
        hashMap.put("Tiền gửi khách hàng", "Deposits from customers");
        hashMap.put("Tổng vốn CSH", "Total owners' equity");
        /// --- Cong ty chung khoan Anh ---///

        hashMap.put("Doanh thu hoạt động", "Total operating revenue");
        hashMap.put("Chi phí hoạt động", "Total operating expense");
        hashMap.put("Kết quả hoạt động", "Net profit from operating activities");
        hashMap.put("Lợi nhuận kế toán trước thuế", "Profit before tax");
        hashMap.put("Lợi nhuận kế toán sau thuế", "Profit after tax");
        hashMap.put("Tổng cộng tài sản", "Total assets");
        hashMap.put("Tài sản ngắn hạn", "Current assets");
        hashMap.put("Nợ phải trả", "Liabilities");
        hashMap.put("Nợ phải trả ngắn hạn", "Current liabilities");
        hashMap.put("Nợ phải trả dài hạn", "Non-current liabilities");
        hashMap.put("Vốn đầu tư CSH", "Shareholder's equity");
        hashMap.put("Vốn góp của CSH", "Charter capital");
        /// --- bao hiem Anh ---///
        hashMap.put("Doanh thu thuần hoạt động kinh doanh bảo hiểm", "Total operating revenue");
        hashMap.put("Lợi nhuận sau thuế TNDN", "Profit after tax");
        hashMap.put("Tổng cộng tài sản", "Total assets");
        hashMap.put("Vốn CSH", "Owners' equity");
        /// --- Chung chi quy Anh ---///
        hashMap.put("Tổng tài sản", "Total assets");
        hashMap.put("Đầu tư chứng khoán", "Investments in securities");
        hashMap.put("Nguồn vốn CSH", "Owners' equity");
        hashMap.put("Thu nhập từ HĐ đầu tư đã thực hiện", "Profit from investing activities");
        hashMap.put("KQHĐ ròng đã thực hiện trong kỳ", "Net realised profit for the year");
        hashMap.put("Lợi nhuận trong năm", "Net (loss)/ profit for the year");
    }
}
